export default {
  SEND_OTP: "SEND_OTP",
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
  REGISTRATION: "REGISTRATION",
  CHANGE_USER: "CHANGE_USER",
  GET_USER_ORDERS: "GET_USER_ORDERS",
  CREATE_ORDER: "CREATE_ORDER",
  CHANGE_FAVORITE: 'CHANGE_FAVORITE',
};
