export default {
  GET_PRODUCTS: "GET_PRODUCTS",
  GET_SALES_PRODUCTS: "GET_SALES_PRODUCTS",
  GET_TOP_PRODUCTS: "GET_TOP_PRODUCTS",
  GET_CATALOG_PRODUCTS: "GET_CATALOG_PRODUCTS",
  GET_SEARCH_SUGGESTIONS: 'GET_SEARCH_SUGGESTIONS',
};
